name: Terraform_LB_Creation                # GH Name/Project Name

on:                                   # Trigger
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:                                        
  Terraform_Build:                                     #Ye hai job ka naam
    runs-on: ubuntu-latest                  #microsoft Hosted

    steps:
      - name: Code Checkout                         #1. Checkout code into Runner
        uses: actions/checkout@v5

      - name: Azure Login                           #2. Azure me login with sp on RBAC
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Install Terraform                        #3. Setup kar liya Terraform ka
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: latest

      - name: Terraform init azurerm backend
        uses: ahmedig/terraform-azurerm-backend@v4
        with:
          azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
          resource_group_name: gunjan-env-rg
          container_name: gunjancontainer
          storage_account_name: unjanenvstg22847
          tf_working_directory: todoapp_infra

      - name: Terraform Validate
        run: terraform validate
        working-directory: todoapp_infra

      - name: Terraform security scan
        uses: triat/terraform-security-scan@v3
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}

      - name: Terraform Lint
        uses: terraform-linters/setup-tflint@v5
        with:
          tflint_version: v0.52.0

      - name: Run TFLint
        run: tflint -f compact

      - name: Terraform Plan
        run: terraform plan
        working-directory: todoapp_infra
  
  Terraform_Deploy:
    runs-on: ubuntu-latest 
    needs: Terraform_Build
    steps:

      - name: Code Checkout                         #1. Checkout code into Runner
        uses: actions/checkout@v5

      - name: Azure Login                           #2. Azure me login with sp on RBAC
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Terraform Apply
        run: terraform Apply --auto-approve
        working-directory: todoapp_infra
